# Generated by Django 4.1.3 on 2022-12-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('reseller_mname', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('reseller_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('reseller_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
                ('reseller_contact', models.CharField(max_length=12, verbose_name='Contact Number')),
                ('reseller_address', models.CharField(max_length=200, verbose_name='Address')),
                ('reseller_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('reseller_id', models.ImageField(default='image_path/dog.jpg', upload_to='image_path')),
                ('reseller_status', models.CharField(choices=[(' ', ' '), ('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], max_length=200, null=True, verbose_name='Status')),
            ],
        ),
    ]
