# Generated by Django 4.1.2 on 2022-12-09 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_Pname',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_pcategory',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_psize',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_qty',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Shipping', 'Out for Shippin'), ('Completed', 'Completed')], max_length=250, null=True, verbose_name='Delivery Option'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_address',
            field=models.TextField(verbose_name='Address'),
        ),
    ]
