# Generated by Django 4.1.3 on 2022-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='reseller_status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], max_length=200, null=True, verbose_name='Status'),
        ),
    ]
