# Generated by Django 4.1.3 on 2022-12-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_remove_transaction_transaction_pname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_fullname',
            field=models.CharField(max_length=250, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Shipping', 'Out for Shipping'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Delivery Option'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_user',
            field=models.CharField(max_length=250, null=True, verbose_name='Transaction User'),
        ),
    ]
