# Generated by Django 4.1.3 on 2022-12-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_alter_transaction_transaction_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_contactno',
            field=models.IntegerField(null=True, verbose_name='Contact Number'),
        ),
    ]
