# Generated by Django 4.1.3 on 2022-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, unique=True, verbose_name='Product Code')),
                ('product_category', models.CharField(max_length=200, verbose_name='Category')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('product_size', models.CharField(max_length=200, verbose_name='Size')),
                ('product_price', models.CharField(max_length=200, verbose_name='Price')),
                ('product_stock', models.CharField(max_length=200, verbose_name='Available Stock')),
                ('product_status', models.CharField(choices=[('available', 'available'), ('n/a', 'n/a')], max_length=200, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
