# Generated by Django 4.1.3 on 2022-12-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_alter_transaction_transaction_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_contactno',
            field=models.BigIntegerField(null=True, verbose_name='Contact Number'),
        ),
    ]
