# Generated by Django 4.1.3 on 2022-12-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_products_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
