# Generated by Django 4.1.3 on 2022-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_alter_transaction_transaction_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_totalprice',
            field=models.CharField(max_length=250, null=True, verbose_name='Total Price'),
        ),
    ]
