# Generated by Django 4.1.3 on 2022-12-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_transaction_transaction_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_totalprice',
            field=models.FloatField(null=True, verbose_name='Total Price'),
        ),
    ]
