# Generated by Django 4.1.3 on 2022-12-03 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_alter_product_product_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_expiry',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 6, 27, 19, 657422, tzinfo=datetime.timezone.utc), null=True, verbose_name='Expiry Date'),
        ),
    ]
