# Generated by Django 4.1.3 on 2022-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_alter_transaction_transaction_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='pos_amount',
            field=models.FloatField(null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_price',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
    ]
