# Generated by Django 4.1.3 on 2022-12-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_alter_pos_pos_amount_alter_pos_pos_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderItem_user', models.CharField(default=None, max_length=200, verbose_name='List user')),
                ('OrderItem_category', models.CharField(max_length=200, verbose_name='Category')),
                ('OrderItem_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('OrderItem_size', models.CharField(max_length=200, verbose_name='Size')),
                ('OrderItem_quantity', models.CharField(max_length=200, null=True, verbose_name='quantity')),
                ('OrderItem_amount', models.FloatField(null=True, verbose_name='Amount')),
            ],
        ),
    ]
