# Generated by Django 4.1.3 on 2022-12-03 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_alter_product_product_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_expiry',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Expiry Date'),
        ),
    ]
