# Generated by Django 4.1.3 on 2022-12-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0010_alter_product_product_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_pcode', models.CharField(max_length=200, unique=True, verbose_name='Product Code')),
                ('pos_category', models.CharField(max_length=200, verbose_name='Category')),
                ('pos_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('pos_size', models.CharField(max_length=200, verbose_name='Size')),
                ('pos_price', models.CharField(max_length=200, verbose_name='Price')),
                ('pos_amount', models.IntegerField(verbose_name='Amount')),
            ],
        ),
    ]
