# Generated by Django 4.1.3 on 2022-12-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0010_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_fullname',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_fname',
            field=models.CharField(max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_lname',
            field=models.CharField(max_length=250, null=True, verbose_name='Last Name'),
        ),
    ]
