# Generated by Django 4.1.3 on 2022-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='pos_user',
            field=models.CharField(default=False, max_length=200, verbose_name='List user'),
        ),
    ]
