# Generated by Django 4.1.3 on 2022-12-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_remove_transaction_transaction_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_delivered',
            field=models.DateTimeField(null=True, verbose_name='Delivered Time'),
        ),
    ]
