# Generated by Django 4.1.3 on 2022-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0012_pos_pos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='pos_pcode',
            field=models.CharField(max_length=200, verbose_name='Product Code'),
        ),
    ]
