# Generated by Django 4.1.3 on 2022-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0013_alter_pos_pos_pcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='pos_user',
            field=models.CharField(default=None, max_length=200, verbose_name='List user'),
        ),
    ]
