# Generated by Django 4.1.3 on 2022-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0014_alter_pos_pos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='pos_quantity',
            field=models.CharField(max_length=200, null=True, verbose_name='quantity'),
        ),
    ]
