# Generated by Django 4.1.3 on 2022-12-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0015_pos_pos_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='reseller_businessp',
            field=models.ImageField(default='image_path/dog.jpg', upload_to='image_path', verbose_name='Business Permit'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='reseller_id',
            field=models.ImageField(default='image_path/dog.jpg', upload_to='image_path', verbose_name='Valid ID'),
        ),
    ]
