# Generated by Django 4.1.3 on 2022-12-06 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0016_reseller_reseller_businessp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='Login Username')),
                ('Activity', models.CharField(max_length=250, verbose_name='Activity')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time')),
            ],
        ),
    ]
