# Generated by Django 4.1.3 on 2022-12-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0017_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='username',
            new_name='user_name',
        ),
    ]
