# Generated by Django 4.1.3 on 2022-12-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0018_rename_username_activitylog_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='Activity',
            new_name='activity',
        ),
    ]
