# Generated by Django 4.1.3 on 2022-12-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0019_rename_activity_activitylog_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activitylog',
            new_name='Activity_log',
        ),
    ]
