# Generated by Django 4.1.3 on 2022-12-07 07:14

import admin_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0022_alter_product_product_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='reseller_businessp',
            field=models.ImageField(default='image_path/dog.jpg', upload_to=admin_site.models.image_path, verbose_name='Business Permit'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='reseller_id',
            field=models.ImageField(default='valid_id/dog.jpg', upload_to=admin_site.models.image_path, verbose_name='Valid ID'),
        ),
    ]
