# Generated by Django 4.1.3 on 2023-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0023_alter_by_batch_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_product',
            name='return_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Returned Completed'),
        ),
    ]
