# Generated by Django 4.1.3 on 2022-12-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0023_alter_reseller_reseller_businessp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='reseller_businessp',
            field=models.ImageField(default='image_path/dog.jpg', upload_to='image_path', verbose_name='Business Permit'),
        ),
    ]
