# Generated by Django 4.1.3 on 2022-12-07 07:29

import admin_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0024_alter_reseller_reseller_businessp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='reseller_businessp',
            field=models.ImageField(default='business_permit/dog.jpg', upload_to=admin_site.models.image_path, verbose_name='Business Permit'),
        ),
    ]
