# Generated by Django 4.1.2 on 2023-05-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0024_return_product_return_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_product',
            name='return_completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Returned Completed'),
        ),
    ]
