# Generated by Django 4.1.3 on 2022-12-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0025_alter_reseller_reseller_businessp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='reseller_businessp',
            field=models.ImageField(default='image_path/dog.jpg', upload_to='image_path'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='reseller_id',
            field=models.ImageField(default='image_path/dog.jpg', upload_to='image_path'),
        ),
    ]
