# Generated by Django 4.1.3 on 2023-03-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0066_alter_by_batch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Status'),
        ),
    ]
