# Generated by Django 4.1.3 on 2023-03-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0067_alter_transaction_transaction_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_no', models.CharField(max_length=250, verbose_name='Promo Code')),
                ('promo_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('promo_discount', models.BigIntegerField(verbose_name='Discount')),
            ],
        ),
    ]
