# Generated by Django 4.1.3 on 2023-03-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0068_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='promo_status',
            field=models.CharField(choices=[('', ''), ('active', 'active'), ('inactive', 'inactive')], max_length=250, null=True, verbose_name='Promo Status'),
        ),
    ]
