# Generated by Django 4.1.3 on 2023-03-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0069_promo_promo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Discount'),
        ),
    ]
